### ISSUE TITLE
interFoam error with fvOptions

### ISSUE THREAD

**Issue by Steph1284** [esteldunedain/airVelocityAttenuation#1]
I tried to use the fvOptions file (copied to my constant folder as described) in my interfoam case (openfoam version 2112).
Unfortunately, I get an error:

[1] --> FOAM FATAL IO ERROR: (openfoam-2112 patch=220610)
[1] Entry 'fields' not found in dictionary "stream.airVelocityAttenuation"

Is there anything more, I need to do, apart from putting the fvOptions file into the constant folder?

**Comment by cibanezu** [comment]
Hi @nicolasbadano, I got to try your sink term implementation in v2412 and it works great. Thanks for sharing it, very handy. 
As the user from this issue has pointed out, copy pasting fvOptions as it is throws an error.
There should be a space after `fields` in this line:
https://github.com/nicolasbadano/airVelocityAttenuation/blob/1ffe6cce0474ec426617a3f85d8750dd6f9f12c4/OpenFOAM-2112/fvOptions#L17
Regards,
Cristóbal

**Comment by nicolasbadano** [comment]
Thank you Cristóbal, I haven't noticed that this issue was reported. Should be fixed now.
